### ISSUE TITLE
Error that crashes the server

### ISSUE THREAD

**Issue by dmccarthy-tssg** [OPENi-ict/notifications#10]
2015-06-02T10:36:08.368Z - info: ----------------------------------------------
[ReferenceError: error is not defined]
ReferenceError: error is not defined
    at postSub (/home/ubuntu/repos/cloudlet-platform/node_modules/notifications/lib/subscription_helper.js:264:13)
    at Object.evaluateMessage (/home/ubuntu/repos/cloudlet-platform/node_modules/notifications/lib/subscription_helper.js:524:10)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/notifications/lib/main.js:71:22
    at /home/ubuntu/repos/cloudlet-platform/node_modules/notifications/node_modules/jsonwebtoken/index.js:65:18
    at process._tickCallback (node.js:442:13)

**Comment by Funi1234** [comment]
fixed in commit 9d33222a7bb8566941f19dd84e09938dbeeeff0b
